### ISSUE TITLE
Allow batch requests

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/genome-nexus#2]
Allow batch requests of variant annotation.  VEP supports:

http://grch37.rest.ensembl.org/vep/human/hgvs/10:g.52595854G%3EA,10:g.52595854G%3EC?content-type=application/json&xref_refseq=1&ccds=1&canonical=1&domains=1&hgvs=1&numbers=1&protein=1

**Comment by onursumer** [comment]
Although VEP supports more than one id in a single query, the resulting JSON for this example query has only one result where <code>"id": "10:g.52595854G>A,10:g.52595854G>C"</code>.

It might be safer to query each id separately and then combine results on our side. What do you think?

**Comment by n1zea144** [comment]
Thats what I thought we would have to do if VEP didn't support the ','.    I think thats fine.

**Comment by onursumer** [comment]
Fixed with PR #6
