### ISSUE TITLE
Use swagger to define client api

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/genome-nexus#4]
Use swagger (swagger.io) to define/document REST api.

**Comment by onursumer** [comment]
Looks like it is possible to integrate swagger into spring boot and use Java annotations to generate swagger documentation: http://heidloff.net/article/usage-of-swagger-2-0-in-spring-boot-applications-to-document-apis/

I think the advantage of this approach is that it eliminates the need of manually configuring a JSON or YAML file. I am still not sure though if this is the best way of using swagger.
